### ISSUE TITLE
Mahony and not Madgwick

### ISSUE THREAD

**Issue by fenaux** [daehwa/Gait-Tracking-With-x-IMU-Python#2]
thanks for making your work available

In script.py line 96 a Mahony filter is initialized and used on line 98
Can you explain the reason for this choice and not a Madgwick filter as in Gait-Tracking-With-x-IMU 

Thanks for you help

**Comment by daehwa** [comment]
This code is a conversion of Seb Madgwick's original post (https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU) in Python. As the original code in MATLAB used a Mahony filter rather than a Madgwick filter, I used it.
From my short knowledge, I guess that he used a Mahony filter because it is more appropriate for a small processor.

Regards,
Daehwa

**Comment by daehwa** [comment]
This code is a conversion of Seb Madgwick's original post (https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU) in Python. As the original code in MATLAB used a Mahony filter rather than a Madgwick filter, I used it.
From my short knowledge, I guess that he would have used a Mahony filter because it is more appropriate for a small processor.

Regards,
Daehwa

**Comment by daehwa** [comment]
Hi,

This code is a conversion of Seb Madgwick's original post (https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU) in Python. As the original code in MATLAB used a Mahony filter rather than a Madgwick filter, I used it.
From my short knowledge, I guess that he would have used a Mahony filter because it is more appropriate for a small processor.

About initialization in line 96 and used on line 98, this code is for the initial convergence of the sensor orientation. If you need to use this code in real-time, this initial convergence process can be done in a few milliseconds.

Regards,
Daehwa
